version: "3.9"
services:
  relay-node:
    container_name: "relay-node"
    image: "eladws/cardano-node"
    ports:
      - "12798:12798"
      - "3001:3001"
    volumes:
      - relay-node-db:/node-db
      - relay-node-ipc:/node-ipc
      - ./cardano/topology-updates:/node-topology
  relay-node-prometheus:
    container_name: "relay-node-prometheus"
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - prometheus-db:/prometheus
      - ./cardano/prometheus:/etc/prometheus
volumes:
    relay-node-db:
    relay-node-ipc:
    prometheus-db:
