version: "3.9"
services:
  relay-node:
    container_name: "relay-node"
    image: "eladws/cardano-node"
    ports:
      - "12789:12798"
      - "3001:3001"
    volumes:
      - cardano-node-db:/cardano/node-db
      - ./topology-updates:/cardano/topology-updates
  relay-node-prometheus:
    container_name: "relay-node-prometheus"
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-db:/prometheus
volumes:
    cardano-node-db:
    prometheus-db:
