version: "3.9"
services:
  core-node:
    container_name: "core-node"
    image: "eladws/cardano-core-node"
    ports:
      - "12798:12798"
      - "5555:5555"
    volumes:
      - core-node-db:/node-db
      - core-node-ipc:/node-ipc
      - ./block-producer-topology:/node-topology
      - ./node-keys:/node-keys
  core-node-prometheus:
    container_name: "core-node-prometheus"
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - prometheus-db:/prometheus
      - ./prometheus-core-node:/etc/prometheus
volumes:
    core-node-db:
    core-node-ipc:
    prometheus-db:
