version: "3.9"
services:
  relay-node:
    container_name: "relay-node"
    image: "${CARDANO_NODE_IMAGE:-eladws/cardano-node}"
    ports:
      - "6666:6666"
    volumes:
      - relay-node-db:/node-db
      - relay-node-ipc:/node-ipc
      - ./node-config:/node-config
      - ./topology-updates:/node-topology
  relay-node-prometheus:
    container_name: "relay-node-prometheus"
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - relay-prometheus-db:/prometheus
      - ./prometheus:/etc/prometheus
volumes:
    relay-node-db:
    relay-node-ipc:
    relay-prometheus-db:

# For WSL on Windows, it is best to first create the flders and then just mount them using:
# volumes:
#   - path-to-local-db-folder:/node-db
